name: 🐏 Firmware builder

on:
  push:
    paths: 
      - '.github/workflows/firmware.yaml'
      - 'firmware/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: docker.io/zmkfirmware/zmk-build-arm:3.5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone ZMK
        run: | 
          git clone --branch main --depth 1 https://github.com/zmkfirmware/zmk.git firmware/b11/zmk
          cp -r firmware/b11/app firmware/b11/zmk

      - name: Add vendor prefix
        run: echo "etzee  etzee" >> firmware/b11/zmk/app/dts/bindings/vendor-prefixes.yaml

      - name: Hook htoyto into ZMK Kconfig
        run: |
          echo 'rsource "src/htoyto/Kconfig"' >> firmware/b11/zmk/app/Kconfig

      - name: Initialize workspace (west init)
        working-directory: firmware/b11/zmk
        run: west init -l app

      - name: Update modules (west update)
        working-directory: firmware/b11/zmk
        run: west update

      - name: Export Zephyr CMake package (west zephyr-export)
        working-directory: firmware/b11/zmk
        run: west zephyr-export

      - name: Build left side
        working-directory: firmware/b11/zmk/app
        run: |
          west build -d build/left -b etzee_b11 -- \
          -DEXTRA_CONF_FILE=boards/arm/etzee_b11/left.conf \
          -DEXTRA_DTC_OVERLAY_FILE=boards/arm/etzee_b11/left.overlay \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build right side
        working-directory: firmware/b11/zmk/app
        run: |
          west build -d build/right -b etzee_b11 -- \
          -DEXTRA_CONF_FILE=boards/arm/etzee_b11/right.conf \
          -DEXTRA_DTC_OVERLAY_FILE=boards/arm/etzee_b11/right.overlay \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Upload left firmware
        uses: actions/upload-artifact@v4
        with:
          name: etzee_b11_left
          path: firmware/b11/zmk/app/build/left/zephyr/zmk.uf2

      - name: Upload right firmware
        uses: actions/upload-artifact@v4
        with:
          name: etzee_b11_right
          path: firmware/b11/zmk/app/build/right/zephyr/zmk.uf2
